---
- name: Install mosh
  xbps:
    pkg: mosh
    state: present

- name: Install mosh firewall rules
  copy:
    src: mosh.rules
    dest: /etc/iptables.d/mosh.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install mosh firewall rules (v6)
  copy:
    src: mosh.6rules
    dest: /etc/ip6tables.d/mosh.6rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
